apiVersion: app/v1
kind: Deployment
metadata:
  name: financeservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financeservice
  template:
    metadata:
      labels:
        app: financeservice

    spec:
      containers:
      - name: peer2peerworkcontract
        # Replace [GCLOUD_PROJECT] with your project ID.
        image: gcr.io/mlpractise/peer2peerworkcontract-financeservice:v1

        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        resources:
          requests:
            memory: "300Mi"
          limits:
            memory: "1000Mi"
        # The traderepository process listens on port 8080 for web traffic by default.
        ports:
        - name: financehttp
          containerPort: 8888
        env:
        - name: PORT
          value: "8888"
